// L1 deterministic text-layer extractor.
//
// Phase A of EXTRACTION_PIPELINE_PLAN.md. The point of this layer
// is that ~80% of POs from established customers are text-PDFs
// (generated by an ERP, not scanned). For those, pulling the text
// layer with `unpdf` is O(ms), free, and gives us EVERY printed
// character verbatim. The dispatcher then feeds that text to
// downstream adapters via `hints.bodyText`, which means:
//
//   - Claude switches from `pdf_document` mode (sends 50-200KB of
//     base64 PDF over the wire on every call) to `pre_extracted_text`
//     mode (sends a few KB of plain text). ~50% cheaper, ~3x faster.
//   - Image-only PDFs (no text layer) are detected here and the
//     dispatcher routes them through OCR instead of wasting an LLM
//     call on gibberish. Eliminates the `image_pdf_no_text` failure
//     mode at its source.
//
// Design choices:
//
//   - `unpdf` over `pdf-parse` because Vercel serverless can't
//     compile pdfjs-dist's `canvas` native dep at build. unpdf is
//     pure JS, edge-compatible, no native deps. Source:
//     https://github.com/unjs/unpdf
//
//   - Lazy import. The module loads fast even on cold start; the
//     pdfjs payload (~1MB) only loads when we actually have a PDF
//     in hand. Fail soft when unpdf isn't installed (returns
//     `extract_failed` and lets the caller fall through to
//     LLM-on-bytes; no crash).
//
//   - 200-char threshold for "usable text". Below that, the layer
//     is treated as image-only: a watermark or stamp can produce
//     20-50 chars on an otherwise-scanned document. 200 chars is
//     enough to recognise if a real PO header is present.
//
//   - Per-page breakdown so `mixed` (some pages text, some image)
//     can route correctly. Common shape: page 1 has a generated
//     header, pages 2-N are scanned line-item photos.
//
// Output shape:
//   {
//     ok: boolean,
//     status: 'has_text' | 'mixed' | 'image_only' | 'extract_failed',
//     page_count: number,
//     char_count: number,
//     body_text: string | null,         // null on image_only / extract_failed
//     page_breakdown: [{ page, chars, has_text }],
//     extractor: 'unpdf' | 'pdf-parse',
//     extractor_version: string | null,
//     latency_ms: number,
//     error: string | null
//   }

const USABLE_TEXT_THRESHOLD = 200;        // chars below this -> route to OCR
const PER_PAGE_TEXT_THRESHOLD = 30;       // chars below this -> page is "image-only"
const MAX_BODY_TEXT_BYTES = 200_000;      // hard ceiling: claude.js trims to 50K anyway

// Heuristic check that the bytes start with %PDF-. The dispatcher
// already has this same gate but we re-check here so the function
// is safe to call on arbitrary bytes from a test or a future
// caller.
const isPdfBytes = (b) => {
  if (!b || !b.length) return false;
  return b[0] === 0x25 && b[1] === 0x50 && b[2] === 0x44 && b[3] === 0x46;
};

// SHA-256 of bytes for the cache key when no document_id is known
// (e.g. inline-attachment runs from inbound email). Uses Node's
// built-in crypto so it's available in the Vercel serverless
// runtime without an extra dep.
export const contentHash = async (bytes) => {
  if (!bytes || !bytes.length) return null;
  // Use the WebCrypto API if it's mounted (edge/runtime); fall back
  // to node:crypto for the classic serverless path.
  try {
    const sub = globalThis.crypto?.subtle;
    if (sub && typeof sub.digest === "function") {
      const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
      // SubtleCrypto wants an ArrayBuffer-backed view; copy to be safe.
      const buf = arr.buffer.slice(arr.byteOffset, arr.byteOffset + arr.byteLength);
      const digest = await sub.digest("SHA-256", buf);
      return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
    }
  } catch (_e) { /* fall through */ }
  const { createHash } = await import("node:crypto");
  return createHash("sha256").update(bytes).digest("hex");
};

// Lazy-load unpdf. If it's not installed, return null and let the
// caller fall back. We never throw on the import path; a missing
// optional dep should not break extraction.
//
// The /* @vite-ignore */ annotation keeps Vite's import-analysis
// plugin from trying to resolve "unpdf" at build time. Without it
// the dev server / vitest pre-bundle step fails when unpdf isn't
// installed (it's an optionalDependency). At runtime in Vercel the
// dynamic import works the same way.
let _unpdfMod = null;
let _unpdfLoadAttempted = false;
const loadUnpdf = async () => {
  if (_unpdfLoadAttempted) return _unpdfMod;
  _unpdfLoadAttempted = true;
  try {
    const modName = "unpdf";
    _unpdfMod = await import(/* @vite-ignore */ modName);
    return _unpdfMod;
  } catch (_err) {
    _unpdfMod = null;
    return null;
  }
};

const summarisePages = (pageTexts) => {
  if (!Array.isArray(pageTexts)) return [];
  return pageTexts.map((t, i) => {
    const chars = (t || "").length;
    return { page: i + 1, chars, has_text: chars >= PER_PAGE_TEXT_THRESHOLD };
  });
};

const classify = (totalChars, pageBreakdown) => {
  if (totalChars < USABLE_TEXT_THRESHOLD) return "image_only";
  const anyImageOnly = pageBreakdown.some((p) => !p.has_text);
  if (anyImageOnly && pageBreakdown.length > 1) return "mixed";
  return "has_text";
};

// Trim body text to the byte ceiling. Avoids accidentally piping a
// 5MB digital tender into the LLM context window.
const trimBodyText = (s) => {
  if (!s) return null;
  if (Buffer.byteLength(s, "utf8") <= MAX_BODY_TEXT_BYTES) return s;
  // Slice on a character boundary; UTF-8 text-PDF output is
  // overwhelmingly ASCII so byte-length and char-length coincide,
  // but be defensive.
  return s.slice(0, MAX_BODY_TEXT_BYTES);
};

// Public API. Caller passes raw bytes. We return the structured
// result; we do NOT touch the database (the dispatcher does that
// so cache lookups stay close to their use-site).
export const extractTextLayer = async ({ bytes, mime }) => {
  const t0 = Date.now();
  const baseFail = (status, error) => ({
    ok: false,
    status,
    page_count: 0,
    char_count: 0,
    body_text: null,
    page_breakdown: [],
    extractor: "unpdf",
    extractor_version: null,
    latency_ms: Date.now() - t0,
    error,
  });

  if (!bytes || !bytes.length) {
    return baseFail("extract_failed", "no bytes provided");
  }
  // L1 only handles PDFs. Image-only files (PNG, JPG) skip L1
  // entirely; the dispatcher routes them straight to L2 OCR.
  if (!isPdfBytes(bytes) && mime !== "application/pdf") {
    return baseFail("extract_failed", "not a pdf");
  }

  const unpdf = await loadUnpdf();
  if (!unpdf) {
    return baseFail("extract_failed", "unpdf not installed");
  }

  // unpdf exposes `extractText(buffer, opts) -> { totalPages, text }`
  // when `mergePages` is true, or `text: string[]` per page when
  // false. We want the per-page array so we can build the
  // breakdown.
  let result;
  try {
    const { extractText, getDocumentProxy } = unpdf;
    const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
    // getDocumentProxy gives us a pdfjs document we can extract from
    // page-by-page. The returned `text` is `string[]` (one per page)
    // when `mergePages: false`.
    const doc = await getDocumentProxy(arr);
    result = await extractText(doc, { mergePages: false });
  } catch (err) {
    return baseFail("extract_failed", err?.message || "unpdf threw");
  }

  // Older unpdf returns `{ totalPages, text }`. `text` may be
  // `string` when mergePages is true, `string[]` otherwise. Be
  // permissive.
  const rawText = result?.text;
  let pageTexts;
  if (Array.isArray(rawText)) {
    pageTexts = rawText.map((t) => String(t || ""));
  } else if (typeof rawText === "string") {
    // Single-page or merged result. Treat as one page.
    pageTexts = [rawText];
  } else {
    return baseFail("extract_failed", "unpdf returned unexpected shape");
  }

  const pageBreakdown = summarisePages(pageTexts);
  const merged = pageTexts.join("\n\n").trim();
  const charCount = merged.length;
  const status = classify(charCount, pageBreakdown);
  const pageCount = result?.totalPages ?? pageTexts.length;

  return {
    ok: status !== "image_only",
    status,
    page_count: pageCount,
    char_count: charCount,
    body_text: status === "image_only" ? null : trimBodyText(merged),
    page_breakdown: pageBreakdown,
    extractor: "unpdf",
    extractor_version: unpdf?.version || null,
    latency_ms: Date.now() - t0,
    error: null,
  };
};

// Small helpers exported for tests + caller-side decisions.
export const looksLikePdf = isPdfBytes;
export const TEXT_LAYER_THRESHOLDS = {
  usable: USABLE_TEXT_THRESHOLD,
  perPage: PER_PAGE_TEXT_THRESHOLD,
  bodyTextBytes: MAX_BODY_TEXT_BYTES,
};
