// L1 deterministic text-layer extractor.
//
// Phase A of EXTRACTION_PIPELINE_PLAN.md. The point of this layer
// is that ~80% of POs from established customers are text-PDFs
// (generated by an ERP, not scanned). For those, pulling the text
// layer with `unpdf` is O(ms), free, and gives us EVERY printed
// character verbatim. The dispatcher then feeds that text to
// downstream adapters via `hints.bodyText`, which means:
//
//   - Claude switches from `pdf_document` mode (sends 50-200KB of
//     base64 PDF over the wire on every call) to `pre_extracted_text`
//     mode (sends a few KB of plain text). ~50% cheaper, ~3x faster.
//   - Image-only PDFs (no text layer) are detected here and the
//     dispatcher routes them through OCR instead of wasting an LLM
//     call on gibberish. Eliminates the `image_pdf_no_text` failure
//     mode at its source.
//
// Design choices:
//
//   - `unpdf` over `pdf-parse` because Vercel serverless can't
//     compile pdfjs-dist's `canvas` native dep at build. unpdf is
//     pure JS, edge-compatible, no native deps. Source:
//     https://github.com/unjs/unpdf
//
//   - Lazy import. The module loads fast even on cold start; the
//     pdfjs payload (~1MB) only loads when we actually have a PDF
//     in hand. Fail soft when unpdf isn't installed (returns
//     `extract_failed` and lets the caller fall through to
//     LLM-on-bytes; no crash).
//
//   - 200-char threshold for "usable text". Below that, the layer
//     is treated as image-only: a watermark or stamp can produce
//     20-50 chars on an otherwise-scanned document. 200 chars is
//     enough to recognise if a real PO header is present.
//
//   - Per-page breakdown so `mixed` (some pages text, some image)
//     can route correctly. Common shape: page 1 has a generated
//     header, pages 2-N are scanned line-item photos.
//
// Output shape:
//   {
//     ok: boolean,
//     status: 'has_text' | 'mixed' | 'image_only' | 'extract_failed',
//     page_count: number,
//     char_count: number,
//     body_text: string | null,         // null on image_only / extract_failed
//     page_breakdown: [{ page, chars, has_text }],
//     extractor: 'unpdf' | 'pdf-parse',
//     extractor_version: string | null,
//     latency_ms: number,
//     error: string | null
//   }

// Structural page-tree read (pdf-lib). Used only to recover page_count when
// text extraction fails — see probePageCount in extractTextLayer.
import { probePdfPageCount } from "./pdf-chunker.js";

const USABLE_TEXT_THRESHOLD = 200;        // chars below this -> route to OCR
const PER_PAGE_TEXT_THRESHOLD = 30;       // chars below this -> page is "image-only"
const MAX_BODY_TEXT_BYTES = 200_000;      // hard ceiling: claude.js trims to 50K anyway

// Heuristic check that the bytes start with %PDF-. The dispatcher
// already has this same gate but we re-check here so the function
// is safe to call on arbitrary bytes from a test or a future
// caller.
const isPdfBytes = (b) => {
  if (!b || !b.length) return false;
  return b[0] === 0x25 && b[1] === 0x50 && b[2] === 0x44 && b[3] === 0x46;
};

// unpdf REJECTS a Node Buffer outright ("Please provide binary data as
// `Uint8Array`, rather than `Buffer`"). Node's Buffer extends Uint8Array, so
// the obvious `bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes)`
// is TRUE for a Buffer and hands the Buffer straight through — which is why
// L1 was failing with extract_failed on effectively every PDF, forcing the
// pipeline onto the paid OCR fallback and leaving char_count at 0 (so the
// selector's long-document rule could never fire either).
// Returns a COPY, deliberately. pdf.js transfers (detaches) the ArrayBuffer it
// is handed, so a zero-copy view would leave the caller's `bytes` detached for
// every later consumer — the geometry pass would silently get nothing, and
// worse, run.js reuses the same `bytes` for the LLM call afterwards. The copy
// costs one document-sized allocation per call and keeps callers isolated.
const toUint8 = (bytes) => {
  if (!bytes) return null;
  return new Uint8Array(bytes);
};

// SHA-256 of bytes for the cache key when no document_id is known
// (e.g. inline-attachment runs from inbound email). Uses Node's
// built-in crypto so it's available in the Vercel serverless
// runtime without an extra dep.
export const contentHash = async (bytes) => {
  if (!bytes || !bytes.length) return null;
  // Use the WebCrypto API if it's mounted (edge/runtime); fall back
  // to node:crypto for the classic serverless path.
  try {
    const sub = globalThis.crypto?.subtle;
    if (sub && typeof sub.digest === "function") {
      const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
      // SubtleCrypto wants an ArrayBuffer-backed view; copy to be safe.
      const buf = arr.buffer.slice(arr.byteOffset, arr.byteOffset + arr.byteLength);
      const digest = await sub.digest("SHA-256", buf);
      return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
    }
  } catch (_e) { /* fall through */ }
  const { createHash } = await import("node:crypto");
  return createHash("sha256").update(bytes).digest("hex");
};

// Lazy-load unpdf. If it's not installed, return null and let the
// caller fall back. We never throw on the import path; a missing
// optional dep should not break extraction.
//
// The /* @vite-ignore */ annotation keeps Vite's import-analysis
// plugin from trying to resolve "unpdf" at build time. Without it
// the dev server / vitest pre-bundle step fails when unpdf isn't
// installed (it's an optionalDependency). At runtime in Vercel the
// dynamic import works the same way.
let _unpdfMod = null;
let _unpdfLoadAttempted = false;
const loadUnpdf = async () => {
  if (_unpdfLoadAttempted) return _unpdfMod;
  _unpdfLoadAttempted = true;
  try {
    const modName = "unpdf";
    _unpdfMod = await import(/* @vite-ignore */ modName);
    return _unpdfMod;
  } catch (_err) {
    _unpdfMod = null;
    return null;
  }
};

const summarisePages = (pageTexts) => {
  if (!Array.isArray(pageTexts)) return [];
  return pageTexts.map((t, i) => {
    const chars = (t || "").length;
    return { page: i + 1, chars, has_text: chars >= PER_PAGE_TEXT_THRESHOLD };
  });
};

const classify = (totalChars, pageBreakdown) => {
  if (totalChars < USABLE_TEXT_THRESHOLD) return "image_only";
  const anyImageOnly = pageBreakdown.some((p) => !p.has_text);
  if (anyImageOnly && pageBreakdown.length > 1) return "mixed";
  return "has_text";
};

// Trim body text to the byte ceiling. Avoids accidentally piping a
// 5MB digital tender into the LLM context window.
const trimBodyText = (s) => {
  if (!s) return null;
  if (Buffer.byteLength(s, "utf8") <= MAX_BODY_TEXT_BYTES) return s;
  // Slice on a character boundary; UTF-8 text-PDF output is
  // overwhelmingly ASCII so byte-length and char-length coincide,
  // but be defensive.
  return s.slice(0, MAX_BODY_TEXT_BYTES);
};

// Public API. Caller passes raw bytes. We return the structured
// result; we do NOT touch the database (the dispatcher does that
// so cache lookups stay close to their use-site).
export const extractTextLayer = async ({ bytes, mime }) => {
  const t0 = Date.now();

  // A PDF whose TEXT is unreadable still has a parseable PAGE TREE. Some
  // generators (SAP / Ariba / GEP purchase orders) defeat unpdf entirely, and
  // reporting page_count: 0 on that failure made the model selector blind:
  // page_count is the only pre-extraction size signal it has (the po_multipage
  // rule), so a 13-page 45-line PO looked like a 0-page doc and went to the
  // cheap tier, which returned a header and zero lines. Probe the count
  // structurally instead. Lazy + best-effort: only runs on the failure path
  // (the success path already has a real count from unpdf), and never throws.
  const probePageCount = async () => {
    if (!bytes || !bytes.length) return 0;
    try {
      return Number(await probePdfPageCount(bytes)) || 0;
    } catch (_e) {
      return 0;
    }
  };

  const baseFail = async (status, error) => ({
    ok: false,
    status,
    page_count: await probePageCount(),
    char_count: 0,
    body_text: null,
    page_breakdown: [],
    extractor: "unpdf",
    extractor_version: null,
    latency_ms: Date.now() - t0,
    error,
  });

  if (!bytes || !bytes.length) {
    return await baseFail("extract_failed", "no bytes provided");
  }
  // L1 only handles PDFs. Image-only files (PNG, JPG) skip L1
  // entirely; the dispatcher routes them straight to L2 OCR.
  if (!isPdfBytes(bytes) && mime !== "application/pdf") {
    return await baseFail("extract_failed", "not a pdf");
  }

  const unpdf = await loadUnpdf();
  if (!unpdf) {
    return await baseFail("extract_failed", "unpdf not installed");
  }

  // unpdf exposes `extractText(buffer, opts) -> { totalPages, text }`
  // when `mergePages` is true, or `text: string[]` per page when
  // false. We want the per-page array so we can build the
  // breakdown.
  let result;
  try {
    const { extractText, getDocumentProxy } = unpdf;
    const arr = toUint8(bytes);
    // getDocumentProxy gives us a pdfjs document we can extract from
    // page-by-page. The returned `text` is `string[]` (one per page)
    // when `mergePages: false`.
    const doc = await getDocumentProxy(arr);
    result = await extractText(doc, { mergePages: false });
  } catch (err) {
    return await baseFail("extract_failed", err?.message || "unpdf threw");
  }

  // Older unpdf returns `{ totalPages, text }`. `text` may be
  // `string` when mergePages is true, `string[]` otherwise. Be
  // permissive.
  const rawText = result?.text;
  let pageTexts;
  if (Array.isArray(rawText)) {
    pageTexts = rawText.map((t) => String(t || ""));
  } else if (typeof rawText === "string") {
    // Single-page or merged result. Treat as one page.
    pageTexts = [rawText];
  } else {
    return await baseFail("extract_failed", "unpdf returned unexpected shape");
  }

  const pageBreakdown = summarisePages(pageTexts);
  const merged = pageTexts.join("\n\n").trim();
  const charCount = merged.length;
  const status = classify(charCount, pageBreakdown);
  const pageCount = result?.totalPages ?? pageTexts.length;

  return {
    ok: status !== "image_only",
    status,
    page_count: pageCount,
    char_count: charCount,
    body_text: status === "image_only" ? null : trimBodyText(merged),
    page_breakdown: pageBreakdown,
    extractor: "unpdf",
    extractor_version: unpdf?.version || null,
    latency_ms: Date.now() - t0,
    error: null,
  };
};

// Small helpers exported for tests + caller-side decisions.
export const looksLikePdf = isPdfBytes;
export const TEXT_LAYER_THRESHOLDS = {
  usable: USABLE_TEXT_THRESHOLD,
  perPage: PER_PAGE_TEXT_THRESHOLD,
  bodyTextBytes: MAX_BODY_TEXT_BYTES,
};

// ───────────────────────────────────────────────────────────────────────────
// Text-layer GEOMETRY, for the evidence-highlight overlay.
//
// A digital PDF already knows where every glyph sits, so the click/hover
// highlight never needed OCR. It was wired to OCR bboxes anyway, and OCR only
// runs when this text layer FAILS — so on an ordinary digital PO no geometry
// was ever produced and the overlay silently rendered nothing.
//
// Emits the same shape the OCR layer does, so bbox-evidence.js can index
// either without caring which produced it:
//   { raw_pages: [{ index, width, height, blocks: [{ text, bbox, confidence }] }] }
//
// Coordinates are absolute page units with a TOP-LEFT origin, matching OCR
// output and CSS overlay positioning. pdf.js reports text in PDF user space
// (origin BOTTOM-left), so y is flipped here — getting this backwards renders
// every highlight mirrored down the page.
// ───────────────────────────────────────────────────────────────────────────

const GEOM_MAX_PAGES = 40;          // bound work on very long documents
const GEOM_MAX_BLOCKS_PER_PAGE = 500;

// Group glyph runs sharing a baseline into one line-level block. Per-item
// boxes are too granular to match against an extracted line: a description
// like "OBARA STD SHANK TWS-092-90-2" arrives as several runs, and matching
// on a 3-character fragment would anchor the highlight to the wrong cell.
const groupItemsIntoLines = (items, pageHeight) => {
  const rows = [];
  for (const it of items) {
    const t = it.transform;
    if (!Array.isArray(t) || t.length < 6) continue;
    const x = Number(t[4]);
    const baseline = Number(t[5]);
    const w = Number(it.width) || 0;
    const h = Number(it.height) || Math.abs(Number(t[3])) || 0;
    if (!Number.isFinite(x) || !Number.isFinite(baseline)) continue;
    const tol = Math.max(2, h * 0.6);
    let row = rows.find((r) => Math.abs(r.baseline - baseline) <= tol);
    if (!row) {
      row = { baseline, minX: x, maxX: x + w, minY: baseline, maxY: baseline + h, parts: [] };
      rows.push(row);
    }
    row.minX = Math.min(row.minX, x);
    row.maxX = Math.max(row.maxX, x + w);
    row.minY = Math.min(row.minY, baseline);
    row.maxY = Math.max(row.maxY, baseline + h);
    row.parts.push({ x, str: it.str });
  }
  return rows
    .map((r) => {
      const text = r.parts.sort((a, b) => a.x - b.x).map((p) => p.str).join(" ").replace(/\s+/g, " ").trim();
      if (!text) return null;
      // Flip PDF (bottom-left) -> UI (top-left).
      const y0 = pageHeight - r.maxY;
      const y1 = pageHeight - r.minY;
      return { text, bbox: [r.minX, y0, r.maxX, y1], confidence: 1 };
    })
    .filter(Boolean)
    .slice(0, GEOM_MAX_BLOCKS_PER_PAGE);
};

// Public: per-page line boxes for a digital PDF, or null when the document
// has no usable text layer (a scan) or unpdf is unavailable. Best-effort —
// never throws, so a geometry failure can't break an extraction run.
export const extractTextBlocks = async ({ bytes, maxPages = GEOM_MAX_PAGES } = {}) => {
  if (!bytes || !bytes.length) return null;
  if (!isPdfBytes(bytes)) return null;
  const unpdf = await loadUnpdf();
  if (!unpdf?.getDocumentProxy) return null;

  let doc;
  try {
    doc = await unpdf.getDocumentProxy(toUint8(bytes));
  } catch (_e) {
    return null;
  }

  const rawPages = [];
  const total = Math.min(Number(doc?.numPages) || 0, maxPages);
  for (let i = 1; i <= total; i++) {
    try {
      const page = await doc.getPage(i);
      const viewport = page.getViewport({ scale: 1 });
      const width = Number(viewport?.width) || 0;
      const height = Number(viewport?.height) || 0;
      if (!(width > 0) || !(height > 0)) continue;
      const content = await page.getTextContent();
      const items = (content?.items || []).filter(
        (it) => it && typeof it.str === "string" && it.str.trim(),
      );
      if (!items.length) continue;
      const blocks = groupItemsIntoLines(items, height);
      if (blocks.length) rawPages.push({ index: i - 1, width, height, blocks });
    } catch (_e) { /* skip the page; a partial index still highlights */ }
  }

  return rawPages.length ? { raw_pages: rawPages, source: "text_layer" } : null;
};
