/*
 * 400_logs_and_analytics.sql  --  Phase 4 of the Anvil seed pack.
 *
 * Purpose
 *   Logs, analytics rollups, and channel artefacts. Bulks the
 *   audit_events table from the per-workflow tracers in phase 300
 *   up to >=250. Adds model_routing_log (120), eval cases + runs +
 *   case_results, agent goals + steps, agent_eval_runs, deploys,
 *   backups, audit_export_runs, injection_test_runs, mcp_call_log,
 *   forecast_snapshots (120), analytics_customer_monthly,
 *   analytics_winloss_daily, rlhf_feedback + rlhf_reward_daily,
 *   push subscriptions + notifications, inbound_email threads +
 *   emails (40/150), inbound_chat configs + messages, voice_configs
 *   + calls + actions, network listings + sourcing queries,
 *   prospecting campaigns + targets + suppressions, edi_partners +
 *   envelopes, plm_systems + boms + changes + sync_state,
 *   vertical_pack_installs, erp_chat sessions + messages, print_jobs.
 *
 * Prerequisites
 *   - Migrations 001..059 applied.
 *   - Phases 100, 200, 300 applied (users, master data, workflow rows
 *     are referenced by FKs).
 *   - Run as service_role with `set app.seed_env = 'staging';`.
 *
 * Idempotency
 *   `on conflict ... do nothing` everywhere. Re-running is a no-op.
 *
 * Deterministic UUID namespace
 *   d7a7e5e4-0001-0004-0001-000000000001
 *
 * Seed marker
 *   `{"seed_marker": "anvil-test-seed-v1"}` merged into every jsonb
 *   payload / metadata / detail / raw column where one exists.
 *
 * Deviations from this prompt
 *   - `backups`: migration 005 schema has no `status` column (just
 *     storage_path, size_bytes, taken_by, notes, created_at). The
 *     matrix's "3 succeeded / 1 failed / 2 in_progress" is encoded
 *     in `notes` instead. Documented in the file.
 *   - `inbound_messages` (the chat-channel table from 039) gets a
 *     modest 24-row seed; the matrix's 150-message figure is for
 *     `inbound_emails` (40 threads + 150 emails covered here).
 *   - `audit_events` count: phase 300 already emitted ~65 tracer
 *     rows. This file adds the remainder so the cumulative count
 *     across the seed pack lands at >=250.
 */

-- ───────────────────────────────────────────────────────────────────
-- 0. ENV GUARD
-- ───────────────────────────────────────────────────────────────────
do $guard$
begin
  if current_setting('app.seed_env', true) is null
     or current_setting('app.seed_env', true) not in ('staging', 'local', 'ci') then
    raise exception 'Refusing to seed: app.seed_env must be set to staging, local, or ci. Got: %',
      coalesce(current_setting('app.seed_env', true), '<unset>');
  end if;
end $guard$;

begin;

do $role$ begin
  begin set local role 'postgres'; exception when others then null; end;
end $role$;

-- ───────────────────────────────────────────────────────────────────
-- 1. AUDIT_EVENTS bulk fill  --  bring cumulative count to >=250
-- ───────────────────────────────────────────────────────────────────
-- Phase 300 emitted ~65 tracer rows (one per order plus extras for
-- approved). We add ~190 more so the total is >=250 across the
-- timeline. Mix of action verbs that mirror the real audit dictionary.
do $audbulk$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
  mgr            uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:mgr.alpha@anvil.test');
  fin            uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:fin.alpha@anvil.test');
  prc            uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:prc.alpha@anvil.test');
  alpha          uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:eng.alpha@anvil.test');
  ops            uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:ops.alpha@anvil.test');
  -- Marker so we can detect prior bulk runs.
  marker_present boolean;
begin
  -- Idempotency guard: skip the entire bulk if we've already run.
  select exists (
    select 1 from audit_events
    where tenant_id = default_tenant
      and detail = 'phase400:audit_bulk_marker'
    limit 1
  ) into marker_present;
  if marker_present then
    return;
  end if;

  -- The marker row first.
  insert into audit_events (tenant_id, actor, actor_role, action, object_type, object_id, after_payload, payload_hash, reason, detail, created_at)
  values (default_tenant, primary_admin, 'admin', 'seed.bulk_marker', 'seed', 'phase400', jsonb_build_object('seed_marker','anvil-test-seed-v1'), encode(digest('phase400:audit_bulk_marker','sha256'),'hex'), 'seed', 'phase400:audit_bulk_marker', now() - interval '90 days');

  -- 200 rows generated by a loop. Action verbs cycle through 10
  -- common types so the audit-dictionary view shows a balanced shape.
  for i in 1..200 loop
    insert into audit_events (tenant_id, actor, actor_role, action, object_type, object_id, after_payload, payload_hash, reason, detail, created_at)
    values (
      default_tenant,
      case (i % 6)
        when 0 then primary_admin
        when 1 then mgr
        when 2 then fin
        when 3 then prc
        when 4 then alpha
        else ops
      end,
      case (i % 6)
        when 0 then 'admin'::obara_role
        when 1 then 'sales_manager'::obara_role
        when 2 then 'finance'::obara_role
        when 3 then 'procurement'::obara_role
        when 4 then 'sales_engineer'::obara_role
        else 'operator'::obara_role
      end,
      case (i % 10)
        when 0 then 'order.amended'
        when 1 then 'order.reconciled'
        when 2 then 'order.exported'
        when 3 then 'invoice.issued'
        when 4 then 'invoice.paid'
        when 5 then 'einvoice.generated'
        when 6 then 'spo.acked'
        when 7 then 'spo.delayed_flagged'
        when 8 then 'amendment.applied'
        else 'doc.scanned'
      end,
      case (i % 10)
        when 0 then 'order'        when 1 then 'order'
        when 2 then 'order'        when 3 then 'invoice'
        when 4 then 'invoice'      when 5 then 'einvoice'
        when 6 then 'source_po'    when 7 then 'source_po'
        when 8 then 'order_amendment' else 'document'
      end,
      'seed-' || lpad(i::text, 6, '0'),
      jsonb_build_object('seed_marker','anvil-test-seed-v1','seq',i),
      encode(digest('phase400:audit:' || i::text, 'sha256'), 'hex'),
      'seed',
      'phase400:bulk:' || i::text,
      now() - ((90 - (i % 60)) || ' days')::interval - ((i % 24) || ' hours')::interval
    );
  end loop;
end $audbulk$;

-- ───────────────────────────────────────────────────────────────────
-- 2. MODEL_ROUTING_LOG  --  120 rows; mix of fallback-fired + primary
-- ───────────────────────────────────────────────────────────────────
do $mrl$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  marker_present boolean;
  ord_id         uuid;
  purposes       text[] := array['extract_po','classify_doc','validate_lines','quote_qa','agent_step','docai_extract','bom_map','reconcile','rlhf_explain','price_compose'];
  i              int;
  fb_fired       boolean;
begin
  select exists (select 1 from model_routing_log where tenant_id = default_tenant and purpose = 'phase400_marker' limit 1) into marker_present;
  if marker_present then return; end if;

  -- Marker row first.
  insert into model_routing_log (tenant_id, order_id, purpose, primary_model, primary_status, primary_confidence,
                                  fallback_model, fallback_reason, fallback_status, total_input_tokens, total_output_tokens,
                                  total_latency_ms, created_at)
  values (default_tenant, null, 'phase400_marker', 'seed', 'ok', 1.000, null, null, null, 0, 0, 0, now() - interval '90 days');

  for i in 1..120 loop
    fb_fired := (i % 5 = 0);
    -- Rotate against the order corpus from phase 300.
    select uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES') into ord_id;
    insert into model_routing_log (tenant_id, order_id, purpose, primary_model, primary_status, primary_confidence,
                                    fallback_model, fallback_reason, fallback_status, total_input_tokens, total_output_tokens,
                                    total_latency_ms, created_at)
    values (
      default_tenant, ord_id,
      purposes[((i - 1) % array_length(purposes,1)) + 1],
      'claude-3-5-sonnet-20241022',
      case when fb_fired then 'low_confidence' else 'ok' end,
      case when fb_fired then 0.45 + (i % 10) * 0.005 else 0.92 + (i % 7) * 0.005 end,
      case when fb_fired then 'mistral-large-2407' else null end,
      case when fb_fired then 'primary_low_confidence' else null end,
      case when fb_fired then 'ok' else null end,
      4500 + (i * 17) % 8000,
      850  + (i * 13) % 1500,
      1100 + (i * 23) % 4000,
      now() - ((90 - (i % 60)) || ' days')::interval - ((i % 24) || ' hours')::interval
    );
  end loop;
end $mrl$;

-- ───────────────────────────────────────────────────────────────────
-- 3. PROCESSING_EVENTS top-up  --  matrix asks for 100 total
-- ───────────────────────────────────────────────────────────────────
-- Phase 300 emitted 100 (2 per order x 50). We add a handful of
-- extra cases that aren't tied to orders so the dashboard's "by
-- event_type" panel shows breadth.
do $pebulk$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  marker_present boolean;
  i              int;
begin
  select exists (select 1 from processing_events where tenant_id = default_tenant and case_id = 'phase400:bulk') into marker_present;
  if marker_present then return; end if;

  insert into processing_events (tenant_id, case_id, event_type, object_type, object_id, detail, duration_ms, created_at)
  values (default_tenant, 'phase400:bulk', 'seed_marker', 'seed', null, jsonb_build_object('seed_marker','anvil-test-seed-v1'), 0, now() - interval '90 days');

  for i in 1..30 loop
    insert into processing_events (tenant_id, case_id, event_type, object_type, object_id, detail, duration_ms, created_at)
    values (
      default_tenant, 'extra:' || i::text,
      case (i % 5) when 0 then 'classify' when 1 then 'route' when 2 then 'redact' when 3 then 'rlhf' else 'fallback' end,
      'system', null,
      jsonb_build_object('seed_marker','anvil-test-seed-v1','seq',i),
      450 + (i * 17) % 1500,
      now() - ((30 - (i % 30)) || ' days')::interval
    );
  end loop;
end $pebulk$;

-- ───────────────────────────────────────────────────────────────────
-- 4. EVAL_CASES + EVAL_RUNS + EVAL_CASE_RESULTS
-- ───────────────────────────────────────────────────────────────────
-- 20 cases across 3 suites (extraction / validation / classification).
-- 5 runs covering all 3 suites (so dashboards can chart trend).
-- eval_case_results: full 5x20 = 100 grid (each run scores every case).
do $eval$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  suites         text[] := array['extraction','validation','classification'];
  i              int;
  j              int;
  v_case_id     text;
  v_suite        text;
  run_id         uuid;
  passed_total   int;
  case_passed    int;
begin
  -- Cases.
  for i in 1..20 loop
    v_suite := suites[((i - 1) % 3) + 1];
    v_case_id := v_suite || '-case-' || lpad(i::text,3,'0');
    insert into eval_cases (id, tenant_id, suite, case_id, description, documents, expected, enabled, created_at)
    values (
      uuid_generate_v5(ns, 'evcase:' || v_case_id),
      default_tenant, v_suite, v_case_id,
      'Seed eval case ' || i::text || ' (' || v_suite || ')',
      jsonb_build_array(jsonb_build_object('storage_path','documents/seed/eval/'||v_case_id||'.pdf','filename',v_case_id||'.pdf','seed_marker','anvil-test-seed-v1')),
      jsonb_build_object('expected_lines', 5 + (i % 4), 'expected_total', 250000 + i * 5000, 'seed_marker','anvil-test-seed-v1'),
      true,
      now() - ((90 - i) || ' days')::interval
    ) on conflict do nothing;
  end loop;

  -- Runs (5 cycles across suites).
  for i in 1..5 loop
    v_suite := suites[((i - 1) % 3) + 1];
    run_id := uuid_generate_v5(ns, 'evrun:' || i::text);
    insert into eval_runs (id, tenant_id, suite, passed, failed, total_score, notes, created_at)
    values (
      run_id, default_tenant, v_suite,
      18 - (i % 3), 2 + (i % 3), 0.9000 - (i % 4) * 0.005,
      'Seed eval run ' || i::text,
      now() - ((30 - i * 5) || ' days')::interval
    ) on conflict (id) do nothing;

    -- Score every one of the 20 cases against this run.
    for j in 1..20 loop
      v_case_id := suites[((j - 1) % 3) + 1] || '-case-' || lpad(j::text,3,'0');
      case_passed := case when (i + j) % 7 = 0 then 0 else 1 end;
      insert into eval_case_results (id, tenant_id, run_id, case_id, passed, failed, score, checks, created_at)
      values (
        uuid_generate_v5(ns, 'evres:' || i::text || ':' || j::text),
        default_tenant, run_id, v_case_id,
        case_passed, 1 - case_passed,
        case when case_passed = 1 then 0.9500 else 0.4000 end,
        jsonb_build_array(jsonb_build_object('check','line_count','passed',case_passed = 1), jsonb_build_object('check','total_value','passed',case_passed = 1), jsonb_build_object('seed_marker','anvil-test-seed-v1')),
        now() - ((30 - i * 5) || ' days')::interval + ((j) || ' minutes')::interval
      ) on conflict (id) do nothing;
    end loop;
  end loop;
end $eval$;

-- ───────────────────────────────────────────────────────────────────
-- 5. AGENT_GOALS + AGENT_STEPS + AGENT_EVAL_RUNS
-- ───────────────────────────────────────────────────────────────────
do $agents$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
  alpha          uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:eng.alpha@anvil.test');
  goal_types     text[] := array['quote_accept_within_14d','ar_collect_by_due_plus_7','missing_doc_followup'];
  goal_statuses  text[] := array['active','active','active','paused','completed','completed','cancelled','failed'];
  i              int;
  k              int;
  g_id           uuid;
  steps          int;
  step_results   text[] := array['ok','ok','ok','skipped','error'];
  ord_id         uuid;
begin
  for i in 1..8 loop
    g_id := uuid_generate_v5(ns, 'agoal:' || i::text);
    select uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES') into ord_id;

    insert into agent_goals (id, tenant_id, goal_type, object_type, object_id, status, due_at,
                              next_run_at, config, created_by, owner_user_id, step_count, last_action_at,
                              last_action, last_error, created_at, updated_at)
    values (
      g_id, default_tenant, goal_types[((i - 1) % array_length(goal_types,1)) + 1],
      'order', ord_id,
      goal_statuses[i],
      now() + interval '14 days',
      now() + interval '1 day',
      jsonb_build_object('seed_marker','anvil-test-seed-v1','max_steps', 8 + i),
      primary_admin, alpha,
      4 + (i % 8),
      now() - interval '4 hours', 'send_reminder_email',
      case when i = 8 then 'Repeated 5xx from SMTP relay.' else null end,
      now() - ((30 + i) || ' days')::interval, now() - (i || ' hours')::interval
    ) on conflict (id) do nothing;

    -- 4-12 steps per goal (4 + i, capped at 12).
    steps := least(12, 4 + i);
    for k in 1..steps loop
      insert into agent_steps (id, tenant_id, goal_id, step_no, thought, action, action_payload, result, result_detail,
                                model_used, tokens_in, tokens_out, cost_usd_cents, created_at)
      values (
        uuid_generate_v5(ns, 'astep:' || i::text || ':' || k::text),
        default_tenant, g_id, k,
        'Seed agent thought for step ' || k::text || ' on goal #' || i::text,
        case (k % 4) when 0 then 'send_email' when 1 then 'noop' when 2 then 'escalate' else 'mark_complete' end,
        jsonb_build_object('seed_marker','anvil-test-seed-v1','step',k),
        step_results[((k - 1) % array_length(step_results,1)) + 1],
        case when (k - 1) % 5 = 4 then 'Recoverable error: 503 from upstream.' else 'OK' end,
        'claude-3-5-sonnet-20241022',
        2200 + k * 80,
        650  + k * 30,
        45 + k * 5,
        now() - ((30 + i) || ' days')::interval + ((k) || ' hours')::interval
      ) on conflict (id) do nothing;
    end loop;
  end loop;

  -- 5 agent_eval_runs (weekly cadence; matrix asks for 5).
  for i in 1..5 loop
    insert into agent_eval_runs (id, tenant_id, ran_at, cases_evaluated, avg_score, summary, sample)
    values (
      uuid_generate_v5(ns, 'aer:' || i::text),
      default_tenant, now() - ((35 - i * 7) || ' days')::interval,
      20 + i, 0.8500 + (i % 3) * 0.01,
      jsonb_build_object('seed_marker','anvil-test-seed-v1','top_drift','quote_qa'),
      jsonb_build_array(jsonb_build_object('case_id','seed-1','score',0.91), jsonb_build_object('case_id','seed-2','score',0.78))
    ) on conflict (id) do nothing;
  end loop;
end $agents$;

-- ───────────────────────────────────────────────────────────────────
-- 6. DEPLOYS  --  8 rows mix of preview + production
-- ───────────────────────────────────────────────────────────────────
insert into deploys (id, commit_sha, environment, deployed_at, deployed_by, branch, url, meta) values
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:1'), encode(digest('a6f5926','sha256'),'hex'), 'production', now() - interval '90 days', 'kenith.philip@fivetran.com', 'main',                  'https://anvil.example/main',         jsonb_build_object('seed_marker','anvil-test-seed-v1')),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:2'), encode(digest('b647f1c','sha256'),'hex'), 'preview',    now() - interval '60 days', 'kenith.philip@fivetran.com', 'sec-followup',          'https://anvil-preview-001.example',  jsonb_build_object('seed_marker','anvil-test-seed-v1')),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:3'), encode(digest('33aee0f','sha256'),'hex'), 'production', now() - interval '30 days', 'kenith.philip@fivetran.com', 'main',                  'https://anvil.example/main',         jsonb_build_object('seed_marker','anvil-test-seed-v1','release','v1.5')),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:4'), encode(digest('seedp1','sha256'),'hex'),  'preview',    now() - interval '14 days', 'kenith.philip@fivetran.com', 'seed-pack-phase-1-2',   'https://anvil-preview-002.example',  jsonb_build_object('seed_marker','anvil-test-seed-v1')),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:5'), encode(digest('seedp3','sha256'),'hex'),  'preview',    now() - interval '7 days',  'kenith.philip@fivetran.com', 'seed-pack-phase-3',     'https://anvil-preview-003.example',  jsonb_build_object('seed_marker','anvil-test-seed-v1')),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:6'), encode(digest('hotfix1','sha256'),'hex'), 'production', now() - interval '5 days',  'kenith.philip@fivetran.com', 'hotfix/csp-tighten',    'https://anvil.example/main',         jsonb_build_object('seed_marker','anvil-test-seed-v1','release','v1.5.1')),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:7'), encode(digest('preview7','sha256'),'hex'),'preview',    now() - interval '3 days',  'kenith.philip@fivetran.com', 'feat/landing-v2',       'https://anvil-preview-004.example',  jsonb_build_object('seed_marker','anvil-test-seed-v1')),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','dep:8'), encode(digest('preview8','sha256'),'hex'),'preview',    now() - interval '1 day',   'kenith.philip@fivetran.com', 'feat/seed-pack-400',    'https://anvil-preview-005.example',  jsonb_build_object('seed_marker','anvil-test-seed-v1'))
on conflict do nothing;

-- ───────────────────────────────────────────────────────────────────
-- 7. BACKUPS  --  6 rows; status encoded in `notes` since the
--    schema has no status column
-- ───────────────────────────────────────────────────────────────────
do $bkup$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
begin
  insert into backups (id, tenant_id, storage_path, size_bytes, taken_by, notes, created_at) values
    (uuid_generate_v5(ns,'bk:1'), default_tenant, 'backups/seed/anvil-2026-04-01.tar.gz', 1024 * 1024 * 540,  primary_admin, 'status=succeeded; nightly full',                       now() - interval '60 days'),
    (uuid_generate_v5(ns,'bk:2'), default_tenant, 'backups/seed/anvil-2026-04-15.tar.gz', 1024 * 1024 * 552,  primary_admin, 'status=succeeded; nightly full',                       now() - interval '45 days'),
    (uuid_generate_v5(ns,'bk:3'), default_tenant, 'backups/seed/anvil-2026-05-01.tar.gz', 1024 * 1024 * 568,  primary_admin, 'status=succeeded; nightly full',                       now() - interval '30 days'),
    (uuid_generate_v5(ns,'bk:4'), default_tenant, 'backups/seed/anvil-2026-05-03.tar.gz', null,               primary_admin, 'status=failed; SIGTERM during pg_dump',                now() - interval '28 days'),
    (uuid_generate_v5(ns,'bk:5'), default_tenant, 'backups/seed/anvil-2026-05-04.tar.gz', null,               primary_admin, 'status=in_progress; pg_dump streaming',                now() - interval '12 hours'),
    (uuid_generate_v5(ns,'bk:6'), default_tenant, 'backups/seed/anvil-2026-05-04b.tar.gz',null,               primary_admin, 'status=in_progress; storage upload in flight',         now() - interval '4 hours')
  on conflict (id) do nothing;
end $bkup$;

-- ───────────────────────────────────────────────────────────────────
-- 8. AUDIT_EXPORT_RUNS  --  4 rows
-- ───────────────────────────────────────────────────────────────────
do $aer$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
begin
  insert into audit_export_runs (id, tenant_id, exported_by, exported_at, from_ts, to_ts, type_filters, rows_exported, signed_hash) values
    (uuid_generate_v5(ns,'aer:1'), default_tenant, primary_admin, now() - interval '40 days', now() - interval '70 days', now() - interval '40 days', array['order','invoice'],  240, encode(digest('aer:1','sha256'),'hex')),
    (uuid_generate_v5(ns,'aer:2'), default_tenant, primary_admin, now() - interval '30 days', now() - interval '60 days', now() - interval '30 days', array['order'],            180, encode(digest('aer:2','sha256'),'hex')),
    (uuid_generate_v5(ns,'aer:3'), default_tenant, primary_admin, now() - interval '15 days', now() - interval '45 days', now() - interval '15 days', array['order','invoice','einvoice'], 410, encode(digest('aer:3','sha256'),'hex')),
    (uuid_generate_v5(ns,'aer:4'), default_tenant, primary_admin, now() - interval '2 days',  now() - interval '32 days', now() - interval '2 days',  array['source_po'],         98, encode(digest('aer:4','sha256'),'hex'))
  on conflict (id) do nothing;
end $aer$;

-- ───────────────────────────────────────────────────────────────────
-- 9. INJECTION_TEST_RUNS  --  3 rows
-- ───────────────────────────────────────────────────────────────────
insert into injection_test_runs (id, tenant_id, catalogue, passed, failed, detail, created_at) values
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','itr:1'), '00000000-0000-0000-0000-000000000001'::uuid, 'owasp-llm-top-10-2024', 38, 2, jsonb_build_array(jsonb_build_object('case','prompt-leak','passed',false), jsonb_build_object('case','sql-injection-via-quote','passed',true), jsonb_build_object('seed_marker','anvil-test-seed-v1')), now() - interval '20 days'),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','itr:2'), '00000000-0000-0000-0000-000000000001'::uuid, 'anvil-internal-redteam-v1', 26, 4, jsonb_build_array(jsonb_build_object('case','tenant-cross','passed',true), jsonb_build_object('case','rls-bypass','passed',true), jsonb_build_object('seed_marker','anvil-test-seed-v1')), now() - interval '10 days'),
  (uuid_generate_v5('d7a7e5e4-0001-0004-0001-000000000001','itr:3'), '00000000-0000-0000-0000-000000000001'::uuid, 'agent-tool-misuse-v1', 14, 1, jsonb_build_array(jsonb_build_object('case','tool-spam','passed',true), jsonb_build_object('seed_marker','anvil-test-seed-v1')), now() - interval '3 days')
on conflict (id) do nothing;

-- ───────────────────────────────────────────────────────────────────
-- 10. MCP_CALL_LOG  --  20 rows (extends mcp_tokens from phase 100)
-- ───────────────────────────────────────────────────────────────────
do $mcp$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  active_tok     uuid := uuid_generate_v5('d7a7e5e4-0001-0001-0001-000000000001','mcp:active');
  i              int;
  tools          text[] := array['read.orders','read.invoices','read.customers','read.inventory','read.pipeline','read.misc'];
  statuses       text[] := array['ok','ok','ok','ok','denied','error'];
  marker_present boolean;
begin
  select exists (select 1 from mcp_call_log where tenant_id = default_tenant and tool = 'phase400_marker' limit 1) into marker_present;
  if marker_present then return; end if;
  insert into mcp_call_log (tenant_id, token_id, tool, scope, args, status, error, latency_ms, rows_returned, ip, user_agent, created_at)
  values (default_tenant, active_tok, 'phase400_marker', null, null, 'ok', null, 0, 0, '127.0.0.1', 'seed', now() - interval '30 days');

  for i in 1..20 loop
    insert into mcp_call_log (tenant_id, token_id, tool, scope, args, status, error, latency_ms, rows_returned, ip, user_agent, created_at)
    values (
      default_tenant, active_tok,
      tools[((i - 1) % array_length(tools,1)) + 1],
      tools[((i - 1) % array_length(tools,1)) + 1],
      jsonb_build_object('seed_marker','anvil-test-seed-v1','seq',i),
      statuses[((i - 1) % array_length(statuses,1)) + 1],
      case when statuses[((i - 1) % array_length(statuses,1)) + 1] = 'error' then 'upstream timeout' else null end,
      120 + (i * 17) % 800,
      case when statuses[((i - 1) % array_length(statuses,1)) + 1] = 'ok' then (i * 7) % 50 else 0 end,
      '203.0.113.' || (50 + (i % 200))::text,
      'Claude/desktop',
      now() - ((30 - i) || ' days')::interval
    );
  end loop;
end $mcp$;

-- ───────────────────────────────────────────────────────────────────
-- 11. FORECAST_SNAPSHOTS  --  120 rows
-- ───────────────────────────────────────────────────────────────────
-- 4 months x 2 segment_dimensions x 15 segment_values = 120.
do $fs$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  d              date;
  dim            text;
  dimensions     text[] := array['territory','customer_type'];
  ter_values     text[] := array['IN-MH','IN-GJ','IN-KA','IN-TN','IN-DL','DE','US-OH','US-MI','JP','KR','CN'];
  ct_values      text[] := array['AUTO_OEM','TIER_ONE','LINE_BUILDER','OTHER'];
  v              text;
  vals           text[];
  k              int;
  cap            int;
begin
  -- 4 monthly snapshots: today, -30d, -60d, -90d.
  for k in 0..3 loop
    d := (now() - (k * 30 || ' days')::interval)::date;
    foreach dim in array dimensions loop
      vals := case dim when 'territory' then ter_values else ct_values end;
      cap := array_length(vals,1);
      for j in 1..15 loop
        v := vals[((j - 1) % cap) + 1];
        insert into forecast_snapshots (id, tenant_id, as_of, segment_dimension, segment_value, open_count, open_amount_inr, weighted_amount_inr, won_count, won_amount_inr, lost_count, lost_amount_inr, next_30_days_amount_inr, next_90_days_amount_inr, generated_at)
        values (
          uuid_generate_v5(ns, 'fs:' || k::text || ':' || dim || ':' || j::text),
          default_tenant, d, dim, v || (case when j > cap then '-' || ((j - 1) / cap)::text else '' end),
          12 + (j * 3) % 18,
          25000000 + (j * 700000) % 18000000,
          12500000 + (j * 320000) % 9000000,
          5 + (j % 10),
          8200000 + (j * 240000) % 6000000,
          2 + (j % 5),
          1500000 + (j * 80000) % 2500000,
          4500000 + (j * 120000) % 3000000,
          12500000 + (j * 240000) % 6500000,
          (now() - (k * 30 || ' days')::interval)::timestamptz
        )
        -- Bug fix May 2026: prior runs left rows whose v5-derived
        -- id matches the current insert's id but whose business
        -- key (tenant, as_of, dim, segment_value) differs because
        -- the segment_value formula was tweaked between phases.
        -- Targeting just the business-key unique constraint then
        -- raised a PK violation on the id. Using the no-target
        -- form catches any unique conflict (PK or business-key)
        -- so the seed stays idempotent regardless of which one
        -- the existing row collides on.
        on conflict do nothing;
      end loop;
    end loop;
  end loop;
end $fs$;

-- ───────────────────────────────────────────────────────────────────
-- 12. ANALYTICS_CUSTOMER_MONTHLY  --  24 rows: 12 months x 2 customers
-- ───────────────────────────────────────────────────────────────────
do $acm$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  mg             uuid;
  jbm            uuid;
  d              date;
  k              int;
begin
  select id into mg  from customers where tenant_id = default_tenant and customer_key = 'MG_MOTOR_INDIA';
  select id into jbm from customers where tenant_id = default_tenant and customer_key = 'NRD_AUTO_PLANT_1';

  for k in 0..11 loop
    d := date_trunc('month', now() - (k * 30 || ' days')::interval)::date;
    if mg is not null then
      insert into analytics_customer_monthly (id, tenant_id, customer_id, month, orders_count, won_count, won_value, win_rate, avg_response_minutes)
      values (uuid_generate_v5(ns,'acm:mg:' || k::text), default_tenant, mg, d,
              12 + (k % 5), 7 + (k % 4), 8200000 + (k % 5) * 250000,
              60.00 + (k % 4) * 2.5, 240 + (k * 17) % 200)
      on conflict (id) do nothing;
    end if;
    if jbm is not null then
      insert into analytics_customer_monthly (id, tenant_id, customer_id, month, orders_count, won_count, won_value, win_rate, avg_response_minutes)
      values (uuid_generate_v5(ns,'acm:jbm:' || k::text), default_tenant, jbm, d,
              9 + (k % 5), 5 + (k % 4), 6200000 + (k % 5) * 200000,
              55.00 + (k % 4) * 2.5, 280 + (k * 17) % 200)
      on conflict (id) do nothing;
    end if;
  end loop;
end $acm$;

-- ───────────────────────────────────────────────────────────────────
-- 13. ANALYTICS_WINLOSS_DAILY  --  30 rows
-- ───────────────────────────────────────────────────────────────────
do $awd$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  alpha          uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:eng.alpha@anvil.test');
  k              int;
begin
  for k in 0..29 loop
    insert into analytics_winloss_daily (id, tenant_id, day, rep_id, customer_tier, quotes_created, quotes_won, quotes_lost, quotes_expired, total_won_value, total_lost_value, median_response_minutes, lost_reasons)
    values (
      uuid_generate_v5(ns,'awd:' || k::text),
      default_tenant, (now() - (k || ' days')::interval)::date, alpha,
      case (k % 4) when 0 then 'strategic' when 1 then 'preferred' when 2 then 'standard' else 'watchlist' end,
      8 + (k % 5), 4 + (k % 3), 1 + (k % 4), (k % 2),
      350000 + (k * 40000) % 1500000, 95000 + (k * 10000) % 250000,
      180 + (k * 13) % 200,
      jsonb_build_object('PRICE_UNDERCUT', (k % 3), 'LEAD_TIME', (k % 4), 'NO_RESPONSE', (k % 2), 'seed_marker','anvil-test-seed-v1')
    ) on conflict (id) do nothing;
  end loop;
end $awd$;

-- ───────────────────────────────────────────────────────────────────
-- 14. RLHF_FEEDBACK + RLHF_REWARD_DAILY
-- ───────────────────────────────────────────────────────────────────
do $rlhf$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  alpha          uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:eng.alpha@anvil.test');
  surfaces       text[] := array['agent','intake','anomaly','bom','quote_qa'];
  surf           text;
  k              int;
begin
  -- 25 feedback rows.
  for k in 1..25 loop
    surf := surfaces[((k - 1) % 5) + 1];
    insert into rlhf_feedback (id, tenant_id, surface, case_id, prompt, output, rating, comment, corrected_output, model, user_id, created_at)
    values (
      uuid_generate_v5(ns,'rlhf:' || k::text),
      default_tenant, surf, null,
      jsonb_build_object('seed_marker','anvil-test-seed-v1','surface',surf),
      jsonb_build_object('seed_marker','anvil-test-seed-v1'),
      case (k % 3) when 0 then -1::smallint else 1::smallint end,  -- 1/3 thumbs-down, rest thumbs-up
      case (k % 4) when 0 then 'Misclassified line; expected SPARES.' else null end,
      case (k % 3) when 0 then jsonb_build_object('correction','Expected mode=SPARES') else null end,
      case (k % 2) when 0 then 'claude-3-5-sonnet-20241022' else 'mistral-large-2407' end,
      alpha,
      now() - (k || ' days')::interval
    ) on conflict (id) do nothing;
  end loop;

  -- 30 reward_daily rows (10 days x 3 surfaces).
  for k in 0..29 loop
    surf := surfaces[((k % 3) + 1)];
    insert into rlhf_reward_daily (id, tenant_id, surface, day, positive, negative, neutral, net_score, comments_count, corrections_count, models)
    values (
      uuid_generate_v5(ns,'rrd:' || k::text),
      default_tenant, surf, (now() - (k || ' days')::interval)::date,
      6 + (k % 4), 1 + (k % 3), 2 + (k % 2), (6 + (k % 4)) - (1 + (k % 3)),
      4 + (k % 3), 2 + (k % 2),
      array['claude-3-5-sonnet-20241022','mistral-large-2407']
    ) on conflict (id) do nothing;
  end loop;
end $rlhf$;

-- ───────────────────────────────────────────────────────────────────
-- 15. PUSH_SUBSCRIPTIONS + PUSH_NOTIFICATIONS
-- ───────────────────────────────────────────────────────────────────
do $push$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
  mgr            uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:mgr.alpha@anvil.test');
  fin            uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:fin.alpha@anvil.test');
  alpha          uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:eng.alpha@anvil.test');
  sub_admin      uuid := uuid_generate_v5(ns,'sub:admin');
  sub_mgr        uuid := uuid_generate_v5(ns,'sub:mgr');
  sub_fin        uuid := uuid_generate_v5(ns,'sub:fin');
  sub_alpha      uuid := uuid_generate_v5(ns,'sub:alpha');
  i              int;
begin
  insert into push_subscriptions (id, tenant_id, user_id, channel, endpoint, auth, device_token, user_agent, is_active, last_seen_at, created_at) values
    (sub_admin, default_tenant, primary_admin, 'web', 'https://fcm.googleapis.com/fcm/send/seed-admin', encode(digest('admin','sha256'),'base64'), null, 'Mozilla/5.0', true,  now() - interval '1 hour',  now() - interval '60 days'),
    (sub_mgr,   default_tenant, mgr,           'web', 'https://fcm.googleapis.com/fcm/send/seed-mgr',   encode(digest('mgr','sha256'),'base64'),   null, 'Mozilla/5.0', true,  now() - interval '6 hours', now() - interval '50 days'),
    (sub_fin,   default_tenant, fin,           'fcm', null, null, 'fcm-token-' || encode(digest('fin','sha256'),'hex'), 'Pixel-7', true,  now() - interval '12 hours', now() - interval '40 days'),
    (sub_alpha, default_tenant, alpha,         'web', 'https://fcm.googleapis.com/fcm/send/seed-alpha', encode(digest('alpha','sha256'),'base64'), null, 'Mozilla/5.0', false, now() - interval '20 days', now() - interval '120 days')
  on conflict (id) do nothing;

  -- 8 notifications: queued / sent / failed / expired x 2.
  for i in 1..8 loop
    insert into push_notifications (id, tenant_id, user_id, subscription_id, title, body, url, data, status, attempt_count, sent_at, error, created_at)
    values (
      uuid_generate_v5(ns,'pn:' || i::text), default_tenant,
      case (i % 4) when 0 then primary_admin when 1 then mgr when 2 then fin else alpha end,
      case (i % 4) when 0 then sub_admin when 1 then sub_mgr when 2 then sub_fin else sub_alpha end,
      case (i % 4) when 0 then 'Approval needed' when 1 then 'Order at risk' when 2 then 'Invoice paid' else 'Daily digest' end,
      'Seed push notification body ' || i::text, '/admin?tab=access',
      jsonb_build_object('seed_marker','anvil-test-seed-v1','seq',i),
      case (i % 4) when 0 then 'queued' when 1 then 'sent' when 2 then 'failed' else 'expired' end,
      case (i % 4) when 0 then 0 when 1 then 1 when 2 then 3 else 2 end,
      case (i % 4) when 1 then now() - (i || ' hours')::interval else null end,
      case (i % 4) when 2 then 'subscription_lapsed' else null end,
      now() - (i || ' hours')::interval
    ) on conflict (id) do nothing;
  end loop;
end $push$;

-- ───────────────────────────────────────────────────────────────────
-- 16. INBOUND_EMAILS  --  40 threads, 150 emails total
-- ───────────────────────────────────────────────────────────────────
do $em$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  thread_id      uuid;
  email_id       uuid;
  email_count    int;
  i              int;
  j              int;
  status_v       text;
  cust_id        uuid;
  cust_keys      text[] := array['MG_MOTOR_INDIA','TATA_MOTORS_PV_PUNE','NRD_AUTO_PLANT_1','ALAP','ANVIL_TEST_INDUSTRIES','GLOBEX_MFG_GMBH','ACME_ROBOTICS_LLC','NIPPON_KOGYO'];
  total_emails   int := 0;
begin
  for i in 1..40 loop
    select id into cust_id from customers where tenant_id = default_tenant and customer_key = cust_keys[((i - 1) % array_length(cust_keys,1)) + 1];
    thread_id := uuid_generate_v5(ns,'iet:' || i::text);
    -- 3-5 messages per thread (deterministic).
    email_count := 3 + (i % 3);

    insert into inbound_email_threads (id, tenant_id, customer_id, thread_key, subject, first_received_at, last_received_at, message_count, status, linked_order_id)
    values (
      thread_id, default_tenant, cust_id,
      'thread-' || encode(digest('thread:' || i::text,'sha256'),'hex'),
      case (i % 4) when 0 then 'PO ' || (5100002500 + i)::text when 1 then 'RFQ for spares' when 2 then 'Invoice query' else 'CAR follow-up' end,
      now() - ((40 - i) || ' days')::interval,
      now() - ((40 - i) || ' days')::interval + ((email_count - 1) || ' days')::interval,
      email_count,
      case (i % 4) when 0 then 'open' when 1 then 'linked' when 2 then 'closed' else 'archived' end,
      case (i % 4) when 1 then uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES') else null end
    ) on conflict (id) do nothing;

    -- Emails. Stop at 150 across all threads.
    for j in 1..email_count loop
      exit when total_emails >= 150;
      total_emails := total_emails + 1;
      email_id := uuid_generate_v5(ns,'ie:' || i::text || ':' || j::text);
      status_v := case ((i + j) % 6)
                    when 0 then 'received'
                    when 1 then 'parsed'
                    when 2 then 'linked'
                    when 3 then 'duplicate'
                    when 4 then 'failed'
                    else 'archived'
                  end;
      insert into inbound_emails (id, tenant_id, thread_id, provider, message_id, in_reply_to, references_chain,
                                   from_address, from_name, to_addresses, cc_addresses, subject, body_text, body_html, raw_mime,
                                   attachments, dup_hash, received_at, parsed_at, linked_order_id, priority_score, customer_id,
                                   customer_tier, status, error, created_at)
      values (
        email_id, default_tenant, thread_id,
        case (i % 3) when 0 then 'postmark' when 1 then 'graph' else 'manual' end,
        '<msg-' || i::text || '-' || j::text || '@seed.example>',
        case j when 1 then null else '<msg-' || i::text || '-' || (j - 1)::text || '@seed.example>' end,
        array['<msg-' || i::text || '-' || j::text || '@seed.example>'],
        'buyer' || i::text || '@customer.example',
        'Buyer ' || i::text,
        array['orders@anvil-seed.test'],
        case (i % 3) when 0 then array['ops@anvil-seed.test'] else array[]::text[] end,
        'Re: ' || (case (i % 4) when 0 then 'PO ' || (5100002500 + i)::text else 'order ' || i::text end),
        'Seed email body ' || i::text || '/' || j::text,
        '<p>Seed email body ' || i::text || '/' || j::text || '</p>',
        null,
        case (j % 2) when 0 then jsonb_build_array(jsonb_build_object('filename','attach.pdf','content_type','application/pdf','size_bytes',95000,'storage_path','documents/seed/inbox/' || i::text || '-' || j::text || '.pdf')) else '[]'::jsonb end,
        encode(digest('iemail:' || i::text || ':' || j::text,'sha256'),'hex'),
        now() - ((40 - i) || ' days')::interval + ((j - 1) || ' days')::interval,
        case status_v when 'received' then null else now() - ((40 - i) || ' days')::interval + ((j - 1) || ' days')::interval + interval '5 minutes' end,
        case status_v when 'linked' then uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES') else null end,
        20 + ((i + j) * 7) % 80,
        cust_id,
        case (i % 4) when 0 then 'strategic' when 1 then 'preferred' when 2 then 'standard' else 'watchlist' end,
        status_v,
        case status_v when 'failed' then 'parser_timeout' else null end,
        now() - ((40 - i) || ' days')::interval + ((j - 1) || ' days')::interval
      ) on conflict (id) do nothing;
    end loop;
  end loop;
end $em$;

-- ───────────────────────────────────────────────────────────────────
-- 17. INBOUND_CHAT_CONFIGS + INBOUND_MESSAGES
-- ───────────────────────────────────────────────────────────────────
do $chat$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  cust_id        uuid;
  i              int;
  ch             text;
  channels       text[] := array['whatsapp','slack','teams','wechat'];
begin
  insert into inbound_chat_configs (id, tenant_id, channel, display_name, creds_plain, active, last_seen_at, last_error, created_at, updated_at) values
    (uuid_generate_v5(ns,'icc:slack'), default_tenant, 'slack', 'Slack: Anvil Internal', jsonb_build_object('seed_marker','anvil-test-seed-v1','workspace','anvil-internal'), true, now() - interval '1 hour', null, now() - interval '120 days', now() - interval '2 days'),
    (uuid_generate_v5(ns,'icc:teams'), default_tenant, 'teams', 'Teams: Anvil Customer', jsonb_build_object('seed_marker','anvil-test-seed-v1','tenant','anvil-customer'), true, now() - interval '4 hours', null, now() - interval '90 days', now() - interval '2 days')
  on conflict (id) do nothing;

  select id into cust_id from customers where tenant_id = default_tenant and customer_key = 'MG_MOTOR_INDIA';

  for i in 1..24 loop
    ch := channels[((i - 1) % 4) + 1];
    insert into inbound_messages (id, tenant_id, customer_id, channel, external_id, thread_external_id, sender_handle, sender_name, text_body, raw_payload, attachments, status, linked_order_id, received_at, processed_at, error)
    values (
      uuid_generate_v5(ns,'imsg:' || i::text), default_tenant, cust_id, ch,
      'ext-' || ch || '-' || i::text,
      'thread-ext-' || (((i - 1) / 4) + 1)::text,
      'buyer-' || i::text,
      'Buyer ' || i::text,
      'Seed chat message #' || i::text || ' on ' || ch,
      jsonb_build_object('seed_marker','anvil-test-seed-v1','channel',ch),
      '[]'::jsonb,
      case (i % 5) when 0 then 'arrived' when 1 then 'intake-extracted' when 2 then 'linked' when 3 then 'resolved' else 'failed' end,
      case (i % 5) when 2 then uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES') else null end,
      now() - (i || ' days')::interval,
      case (i % 5) when 0 then null else now() - (i || ' days')::interval + interval '5 minutes' end,
      case (i % 5) when 4 then 'parser_error' else null end
    ) on conflict (id) do nothing;
  end loop;
end $chat$;

-- ───────────────────────────────────────────────────────────────────
-- 18. VOICE_CONFIGS + VOICE_CALLS + VOICE_CALL_ACTIONS
-- ───────────────────────────────────────────────────────────────────
do $voice$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  config_id      uuid := uuid_generate_v5(ns,'vc:vapi');
  cust_id        uuid;
  call_id        uuid;
  i              int;
  call_statuses  text[] := array['in_progress','completed','completed','failed','escalated'];
begin
  insert into voice_configs (id, tenant_id, provider, display_name, api_key, webhook_secret, phone_number, assistant_id, voice_persona, system_prompt, handoff_phone_number, active, created_at, updated_at)
  values (config_id, default_tenant, 'vapi', 'Anvil Sales (Vapi)', 'va_seed_' || encode(digest('vapi','sha256'),'hex'), encode(digest('vapi-secret','sha256'),'hex'), '+91 11 5550 0000', 'asst_seed_001', 'sales_friendly', 'You are Anvil Sales. Help with orders.', '+91 11 5550 0099', true, now() - interval '60 days', now() - interval '4 days')
  on conflict (id) do nothing;

  select id into cust_id from customers where tenant_id = default_tenant and customer_key = 'MG_MOTOR_INDIA';

  for i in 1..5 loop
    call_id := uuid_generate_v5(ns,'vcall:' || i::text);
    insert into voice_calls (id, tenant_id, config_id, provider, external_id, direction, customer_id, caller_phone_number, callee_phone_number, started_at, ended_at, duration_seconds, status, transcript, summary, action_extracted, raw)
    values (
      call_id, default_tenant, config_id, 'vapi', 'vapi_call_' || lpad(i::text,8,'0'),
      case (i % 2) when 0 then 'inbound' else 'outbound' end,
      cust_id,
      '+91 98 0000 ' || lpad(i::text,4,'0'),
      '+91 11 5550 0000',
      now() - (i || ' days')::interval,
      case call_statuses[i] when 'in_progress' then null else now() - (i || ' days')::interval + interval '4 minutes' end,
      case call_statuses[i] when 'in_progress' then null else 240 + (i * 17) % 200 end,
      call_statuses[i],
      jsonb_build_array(jsonb_build_object('role','user','text','Hello, calling about PO ' || (5100002500 + i)::text), jsonb_build_object('role','assistant','text','Sure, I can help.'), jsonb_build_object('seed_marker','anvil-test-seed-v1')),
      'Seed call ' || i::text,
      jsonb_build_object('seed_marker','anvil-test-seed-v1','intent', case (i % 3) when 0 then 'place_order' when 1 then 'check_delivery' else 'quote_request' end),
      jsonb_build_object('seed_marker','anvil-test-seed-v1','provider','vapi')
    ) on conflict (id) do nothing;

    -- 3 of 5 calls produce extracted actions.
    if i in (1, 3, 5) then
      insert into voice_call_actions (id, tenant_id, call_id, action, payload, completed, result, error, created_at, completed_at)
      values (
        uuid_generate_v5(ns,'vca:' || i::text), default_tenant, call_id,
        case (i % 5) when 1 then 'place_order' when 3 then 'check_delivery' else 'quote_request' end,
        jsonb_build_object('seed_marker','anvil-test-seed-v1','call_seq',i),
        i in (1, 3),
        case when i in (1, 3) then jsonb_build_object('result','dispatched','seed_marker','anvil-test-seed-v1') else null end,
        case when i = 5 then 'agent_routed_to_human' else null end,
        now() - (i || ' days')::interval + interval '3 minutes',
        case when i in (1, 3) then now() - (i || ' days')::interval + interval '5 minutes' else null end
      ) on conflict (id) do nothing;
    end if;
  end loop;
end $voice$;

-- ───────────────────────────────────────────────────────────────────
-- 19. NETWORK_LISTINGS + NETWORK_SOURCING_QUERIES
-- ───────────────────────────────────────────────────────────────────
do $net$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  i              int;
  q_id           uuid;
begin
  -- 30 listings.
  for i in 1..30 loop
    insert into network_listings (id, tenant_id, sku, description, uom, available_qty, lead_time_days, currency, transfer_unit_price, notes, active, source, source_ref, refreshed_at, created_at, updated_at)
    values (
      uuid_generate_v5(ns,'nl:' || i::text),
      default_tenant,
      -- network_listings has unique (tenant_id, sku); on a single
      -- tenant we can't have 5 SKUs x 6 listings. Suffix the SKU
      -- with the iteration number so 30 distinct listings land.
      (case (i % 5) when 0 then 'CT-16-D-1-FS' when 1 then '4-HD32208-2' when 2 then 'X2C-X-MEDIUM' when 3 then 'TIP-Y-2026' else 'CABLE-Y-2026' end) || '/' || lpad(i::text,2,'0'),
      'Seed listing ' || i::text, case (i % 5) when 4 then 'Mtr' else 'Nos' end,
      100 + (i * 17) % 800,
      7 + (i % 14),
      case (i % 4) when 0 then 'INR' when 1 then 'USD' when 2 then 'EUR' else 'JPY' end,
      0.85 + (i % 8) * 0.02, 'Seed listing.', i % 7 <> 0,
      case (i % 3) when 0 then 'manual' when 1 then 'erp_sync' else 'inventory_mirror' end,
      'ref-' || lpad(i::text,5,'0'),
      now() - (i || ' hours')::interval,
      now() - (i || ' days')::interval, now() - (i || ' hours')::interval
    ) on conflict (id) do nothing;
  end loop;

  -- 4 queries with match_count varying.
  for i in 1..4 loop
    q_id := uuid_generate_v5(ns,'nsq:' || i::text);
    insert into network_sourcing_queries (id, tenant_id, order_id, sku, qty_needed, needed_by, match_count, matched_tenant_ids, resolved, resolved_listing_id, resolved_at, created_at)
    values (
      q_id, default_tenant,
      uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES'),
      case i when 1 then 'CT-16-D-1-FS' when 2 then 'X2C-X-MEDIUM' when 3 then 'TIP-Y-2026' else 'CABLE-Y-2026' end,
      100 * i,
      (now() + interval '14 days')::date,
      5 + i * 2,
      array[default_tenant],
      i in (2, 3),
      case when i in (2, 3) then uuid_generate_v5(ns,'nl:' || i::text) else null end,
      case when i in (2, 3) then now() - (i || ' days')::interval else null end,
      now() - ((10 - i) || ' days')::interval
    ) on conflict (id) do nothing;
  end loop;
end $net$;

-- ───────────────────────────────────────────────────────────────────
-- 20. PROSPECTING_CAMPAIGNS + TARGETS + SUPPRESSIONS
-- ───────────────────────────────────────────────────────────────────
do $pros$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
  c_id           uuid;
  i              int;
  k              int;
  -- One campaign per status so verify §2b sees every value at least
  -- once (matrix's 3-campaign target is loose; bumping to 4 keeps the
  -- coverage assertion green without changing downstream targets).
  campaign_statuses text[] := array['active','paused','draft','archived'];
  target_statuses   text[] := array['pending','approved','sent','bounced','replied','unsubscribed','denied'];
  campaign_keys     text[] := array['ICP-paper','ICP-fasteners','ICP-PVF','ICP-electrical'];
  c                 text;
begin
  -- 4 campaigns covering every status value.
  for i in 1..4 loop
    c := campaign_keys[i];
    c_id := uuid_generate_v5(ns,'pc:' || c);
    insert into prospecting_campaigns (id, tenant_id, name, description, template_subject, template_body, daily_send_cap, status, created_by, created_at, updated_at)
    values (c_id, default_tenant, c, 'Seed prospecting campaign ' || c,
            'Re: ' || c || ' lead-time tooling',
            'Hi {{first_name}}, ...',
            100, campaign_statuses[i], primary_admin,
            now() - ((30 + i * 5) || ' days')::interval, now() - (i || ' days')::interval)
    on conflict (id) do nothing;

    -- 10 targets per campaign = 30 total.
    for k in 1..10 loop
      insert into prospecting_targets (id, tenant_id, campaign_id, email, display_name, company, title, source, score, metadata, status, approved_by, approved_at, sent_at, bounced_at, replied_at)
      values (
        uuid_generate_v5(ns,'pt:' || c || ':' || k::text),
        default_tenant, c_id,
        'prospect-' || c || '-' || k::text || '@target.example',
        'Prospect ' || k::text, 'Target Co. ' || k::text, 'Buyer',
        case (k % 3) when 0 then 'apollo' when 1 then 'zoominfo' else 'manual' end,
        50 + (k * 5) % 50,
        jsonb_build_object('seed_marker','anvil-test-seed-v1','campaign',c),
        target_statuses[((k - 1) % 7) + 1],
        case when target_statuses[((k - 1) % 7) + 1] in ('approved','sent','replied','bounced','unsubscribed') then primary_admin else null end,
        case when target_statuses[((k - 1) % 7) + 1] in ('approved','sent','replied','bounced','unsubscribed') then now() - ((20 - k) || ' days')::interval else null end,
        case when target_statuses[((k - 1) % 7) + 1] in ('sent','replied','bounced','unsubscribed') then now() - ((10 - k % 10) || ' days')::interval else null end,
        case when target_statuses[((k - 1) % 7) + 1] = 'bounced' then now() - interval '4 days' else null end,
        case when target_statuses[((k - 1) % 7) + 1] = 'replied' then now() - interval '2 days' else null end
      ) on conflict (id) do nothing;
    end loop;
  end loop;

  -- 8 suppressions (mix tenant + global).
  for i in 1..8 loop
    insert into prospecting_suppressions (id, tenant_id, email, reason, added_at)
    values (
      uuid_generate_v5(ns,'ps:' || i::text),
      case (i % 4) when 0 then null else default_tenant end,
      'unsub' || i::text || '@target.example',
      case (i % 3) when 0 then 'unsubscribed' when 1 then 'bounced_hard' else 'manual' end,
      now() - (i || ' days')::interval
    ) on conflict (id) do nothing;
  end loop;
end $pros$;

-- ───────────────────────────────────────────────────────────────────
-- 21. EDI_PARTNERS + EDI_ENVELOPES
-- ───────────────────────────────────────────────────────────────────
do $edi$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  partner_id     uuid;
  partners       text[] := array['Vega Motor X12','Tata X12','Globex EDIFACT','Acme X12'];
  formats        text[] := array['x12','x12','edifact','x12'];
  i              int;
  k              int;
  msg_types      text[] := array['850','855','810','856','ORDERS','ORDRSP'];
  statuses       text[] := array['received','translated','linked','sent','acknowledged','failed'];
begin
  for i in 1..4 loop
    partner_id := uuid_generate_v5(ns,'edip:' || i::text);
    insert into edi_partners (id, tenant_id, name, isa_qualifier, isa_id, partner_isa_qualifier, partner_isa_id, default_format, envelopes_in, envelopes_out, active, created_at)
    values (partner_id, default_tenant, partners[i], 'ZZ', 'ANVIL00' || i::text, 'ZZ', 'PARTNER0' || i::text, formats[i], 6, 4, true, now() - ((100 + i * 5) || ' days')::interval)
    on conflict (id) do nothing;

    -- 3 envelopes per partner = 12 total covering 6 statuses.
    for k in 1..3 loop
      insert into edi_envelopes (id, tenant_id, partner_id, direction, format, message_type, control_number, raw_payload, parsed, status, order_id, invoice_id, error, ack_payload, created_at, acknowledged_at)
      values (
        uuid_generate_v5(ns,'edie:' || i::text || ':' || k::text),
        default_tenant, partner_id,
        case (k % 2) when 0 then 'inbound' else 'outbound' end,
        formats[i],
        msg_types[((i + k - 1) % array_length(msg_types,1)) + 1],
        lpad(((i * 100) + k)::text, 9, '0'),
        'ISA*00*          *00*          *ZZ*ANVIL00' || i::text || '       *ZZ*PARTNER0' || i::text || '       *240501*1200*U*00501*' || lpad(((i * 100) + k)::text, 9, '0') || '*0*P*>~ ...seed... ~IEA*1*' || lpad(((i * 100) + k)::text, 9, '0') || '~',
        jsonb_build_object('seed_marker','anvil-test-seed-v1'),
        statuses[((i + k - 1) % array_length(statuses,1)) + 1],
        case (k % 2) when 1 then uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES') else null end,
        case (k % 2) when 0 then uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'inv:1') else null end,
        case statuses[((i + k - 1) % array_length(statuses,1)) + 1] when 'failed' then 'parser_error' else null end,
        case statuses[((i + k - 1) % array_length(statuses,1)) + 1] when 'acknowledged' then 'ISA*00*...997...IEA*1*' else null end,
        now() - ((50 - i * 2 - k) || ' days')::interval,
        case statuses[((i + k - 1) % array_length(statuses,1)) + 1] when 'acknowledged' then now() - ((48 - i * 2 - k) || ' days')::interval else null end
      ) on conflict (id) do nothing;
    end loop;
  end loop;
end $edi$;

-- ───────────────────────────────────────────────────────────────────
-- 22. PLM_SYSTEMS + PLM_BOMS + PLM_CHANGES + PLM_SYNC_STATE
-- ───────────────────────────────────────────────────────────────────
do $plm$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  wc_id          uuid := uuid_generate_v5(ns,'plm:wc');
  ar_id          uuid := uuid_generate_v5(ns,'plm:ar');
  i              int;
begin
  insert into plm_systems (id, tenant_id, system, display_name, base_url, username, active, connected_at, last_error, raw, created_at, updated_at) values
    (wc_id, default_tenant, 'windchill', 'Windchill (staging)', 'https://windchill.example.com', 'svc.anvil', true, now() - interval '90 days', null, jsonb_build_object('seed_marker','anvil-test-seed-v1'), now() - interval '120 days', now() - interval '4 days'),
    (ar_id, default_tenant, 'arena',     'Arena (staging)',     'https://app.bom.com',           'svc.anvil', true, now() - interval '60 days', null, jsonb_build_object('seed_marker','anvil-test-seed-v1'), now() - interval '90 days',  now() - interval '4 days')
  on conflict (id) do nothing;

  -- 5 BOMs across the two systems.
  for i in 1..5 loop
    insert into plm_boms (id, tenant_id, source_system, external_id, part_number, description, revision, state, structure, flat_count, raw, synced_at, created_at)
    values (
      uuid_generate_v5(ns,'plmb:' || i::text), default_tenant,
      case (i % 2) when 0 then 'arena' else 'windchill' end,
      'OID-' || lpad(i::text,6,'0'),
      case i when 1 then 'X2C-BASE-ASSY' when 2 then 'SUB-ARM' when 3 then 'SUB-ELECTRODE' when 4 then 'X3-X-MEDIUM' else 'X4-X-TRIAL' end,
      'Seed BOM ' || i::text, 'A',
      case (i % 3) when 0 then 'released' when 1 then 'in-work' else 'released' end,
      jsonb_build_object('seed_marker','anvil-test-seed-v1','levels',2),
      4 + (i % 5),
      jsonb_build_object('seed_marker','anvil-test-seed-v1'),
      now() - (i || ' days')::interval,
      now() - ((10 + i) || ' days')::interval
    ) on conflict (id) do nothing;
  end loop;

  -- 8 changes (ECOs).
  for i in 1..8 loop
    insert into plm_changes (id, tenant_id, source_system, external_id, eco_number, title, description, status, affected_parts, effective_date, raw, synced_at, created_at)
    values (
      uuid_generate_v5(ns,'plmc:' || i::text), default_tenant,
      case (i % 2) when 0 then 'arena' else 'windchill' end,
      'CHG-' || lpad(i::text,6,'0'),
      'ECO-' || lpad(i::text,5,'0'),
      'Seed ECO ' || i::text,
      'Seed change description ' || i::text,
      case (i % 3) when 0 then 'released' when 1 then 'open' else 'rejected' end,
      array['CT-16-D-1-FS','4-HD32208-2'],
      (now() + (i || ' days')::interval)::date,
      jsonb_build_object('seed_marker','anvil-test-seed-v1'),
      now() - (i || ' days')::interval,
      now() - ((10 + i) || ' days')::interval
    ) on conflict (id) do nothing;
  end loop;

  -- Sync state for each system + entity (boms, changes).
  insert into plm_sync_state (id, tenant_id, system_id, entity, last_sync_at, last_modified_high_water, rows_pulled, rows_updated, status, last_error) values
    (uuid_generate_v5(ns,'plmss:wc:boms'),    default_tenant, wc_id, 'boms',    now() - interval '4 hours',  now() - interval '6 hours', 12, 8,  'idle',    null),
    (uuid_generate_v5(ns,'plmss:wc:changes'), default_tenant, wc_id, 'changes', now() - interval '4 hours',  now() - interval '6 hours',  6, 4,  'idle',    null),
    (uuid_generate_v5(ns,'plmss:ar:boms'),    default_tenant, ar_id, 'boms',    now() - interval '12 hours', now() - interval '14 hours', 9, 5,  'running', null),
    (uuid_generate_v5(ns,'plmss:ar:changes'), default_tenant, ar_id, 'changes', now() - interval '24 hours', now() - interval '24 hours', 0, 0,  'error',   'auth_token_expired')
  on conflict (id) do nothing;
end $plm$;

-- ───────────────────────────────────────────────────────────────────
-- 23. VERTICAL_PACK_INSTALLS  --  3 packs
-- ───────────────────────────────────────────────────────────────────
do $vp$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
begin
  insert into vertical_pack_installs (id, tenant_id, vertical_id, pack_version, content_hash, installed_by, installed_at, details) values
    (uuid_generate_v5(ns,'vpi:welding'),  default_tenant, 'welding-equipment',     1, encode(digest('welding-v1','sha256'),'hex'),     primary_admin, now() - interval '60 days', jsonb_build_object('seed_marker','anvil-test-seed-v1','tables',jsonb_build_array('approval_thresholds','admin_lead_times'))),
    (uuid_generate_v5(ns,'vpi:auto'),     default_tenant, 'automotive-tier1',      1, encode(digest('automotive-v1','sha256'),'hex'),  primary_admin, now() - interval '40 days', jsonb_build_object('seed_marker','anvil-test-seed-v1','tables',jsonb_build_array('approval_thresholds'))),
    (uuid_generate_v5(ns,'vpi:autooem'),  default_tenant, 'auto-OEM',              1, encode(digest('auto-oem-v1','sha256'),'hex'),    primary_admin, now() - interval '20 days', jsonb_build_object('seed_marker','anvil-test-seed-v1','tables',jsonb_build_array('admin_lost_reasons')))
  on conflict (id) do nothing;
end $vp$;

-- ───────────────────────────────────────────────────────────────────
-- 24. ERP_CHAT_SESSIONS + ERP_CHAT_MESSAGES
-- ───────────────────────────────────────────────────────────────────
do $erpc$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  primary_admin  uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:admin.primary@anvil.test');
  fin            uuid := uuid_generate_v5(uuid_ns_dns(), 'anvil-seed-user:fin.alpha@anvil.test');
  s_id           uuid;
  i              int;
  k              int;
  msg_count      int;
  roles          text[] := array['user','assistant','tool'];
begin
  for i in 1..4 loop
    s_id := uuid_generate_v5(ns,'es:' || i::text);
    insert into erp_chat_sessions (id, tenant_id, user_id, title, scope, created_at, updated_at)
    values (s_id, default_tenant, case (i % 2) when 0 then primary_admin else fin end,
            'Seed ERP chat session ' || i::text,
            jsonb_build_object('seed_marker','anvil-test-seed-v1','erps',jsonb_build_array('netsuite','sap')),
            now() - ((30 - i * 5) || ' days')::interval, now() - (i || ' days')::interval)
    on conflict (id) do nothing;

    msg_count := 6 + (i * 3); -- 9, 12, 15, 18 = totals 54
    for k in 1..msg_count loop
      insert into erp_chat_messages (id, tenant_id, session_id, role, content, tool_call, tool_result, citations, model, latency_ms, tokens_in, tokens_out, created_at)
      values (
        uuid_generate_v5(ns,'em:' || i::text || ':' || k::text),
        default_tenant, s_id,
        roles[((k - 1) % 3) + 1],
        'Seed message ' || k::text || ' in session ' || i::text,
        case roles[((k - 1) % 3) + 1] when 'tool' then jsonb_build_object('name','netsuite_open_orders','query','top 5','seed_marker','anvil-test-seed-v1') else null end,
        case roles[((k - 1) % 3) + 1] when 'tool' then jsonb_build_object('rows',jsonb_build_array(jsonb_build_object('id','seed-1'),jsonb_build_object('id','seed-2')),'seed_marker','anvil-test-seed-v1') else null end,
        case roles[((k - 1) % 3) + 1] when 'assistant' then jsonb_build_array(jsonb_build_object('source','netsuite_open_orders','ids',jsonb_build_array('seed-1','seed-2'))) else '[]'::jsonb end,
        'claude-3-5-sonnet-20241022',
        450 + (k * 13) % 800,
        2200 + k * 80,
        650 + k * 30,
        now() - ((30 - i * 5) || ' days')::interval + ((k * 30) || ' seconds')::interval
      ) on conflict (id) do nothing;
    end loop;
  end loop;
end $erpc$;

-- ───────────────────────────────────────────────────────────────────
-- 25. PRINT_JOBS  --  8 covering queued / printing / printed / failed / cancelled
-- ───────────────────────────────────────────────────────────────────
do $pj$
declare
  default_tenant uuid := '00000000-0000-0000-0000-000000000001';
  ns             uuid := 'd7a7e5e4-0001-0004-0001-000000000001';
  i              int;
  statuses       text[] := array['queued','printing','printed','printed','failed','cancelled','printed','queued'];
  triggers       text[] := array['erp_push','erp_push','erp_push','manual','erp_push','manual','reorder','erp_push'];
  ord_id         uuid;
begin
  for i in 1..8 loop
    select uuid_generate_v5('d7a7e5e4-0001-0003-0001-000000000001', 'order:APPROVED:SPARES') into ord_id;
    insert into print_jobs (id, tenant_id, order_id, printer_id, pdf_storage_path, pdf_signed_url, status, attempt_count, last_attempt_at, error, triggered_by, created_at, updated_at)
    values (
      uuid_generate_v5(ns,'pj:' || i::text), default_tenant, ord_id,
      'printer-halol-floor-' || ((i % 3) + 1)::text,
      'travelers/seed/' || i::text || '.pdf',
      case statuses[i] when 'printed' then 'https://example.com/signed/' || i::text else null end,
      statuses[i],
      case statuses[i] when 'failed' then 3 else 1 end,
      case statuses[i] when 'queued' then null else now() - (i || ' hours')::interval end,
      case statuses[i] when 'failed' then 'cups_err_503' else null end,
      triggers[i],
      now() - (i || ' hours')::interval, now() - (i || ' minutes')::interval
    ) on conflict (id) do nothing;
  end loop;
end $pj$;

commit;
